//
// PLEASE DO NOT EDIT!!
// This file was generated by scripts/codegen.py, go edit that instead!
//

namespace Sandbox.Sdf;

partial class Sdf3DMeshWriter
{
	partial void AddTriangles( in Sdf3DArrayData data, int x, int y, int z )
	{
		var aRaw = data[x + 0, y + 0, z + 0];
		var bRaw = data[x + 1, y + 0, z + 0];
		var cRaw = data[x + 0, y + 1, z + 0];
		var dRaw = data[x + 1, y + 1, z + 0];

		var eRaw = data[x + 0, y + 0, z + 1];
		var fRaw = data[x + 1, y + 0, z + 1];
		var gRaw = data[x + 0, y + 1, z + 1];
		var hRaw = data[x + 1, y + 1, z + 1];

		var a = aRaw < 128 ? CubeConfiguration.A : 0;
		var b = bRaw < 128 ? CubeConfiguration.B : 0;
		var c = cRaw < 128 ? CubeConfiguration.C : 0;
		var d = dRaw < 128 ? CubeConfiguration.D : 0;

		var e = eRaw < 128 ? CubeConfiguration.A : 0;
		var f = fRaw < 128 ? CubeConfiguration.B : 0;
		var g = gRaw < 128 ? CubeConfiguration.C : 0;
		var h = hRaw < 128 ? CubeConfiguration.D : 0;

		var config = a | b | c | d | e | f | g | h;

		switch ( config )
		{
			case CubeConfiguration.None:
				return;
			case CubeConfiguration.A:
				return;
			case CubeConfiguration.B:
				return;
			case CubeConfiguration.A | CubeConfiguration.B:
				return;
			case CubeConfiguration.C:
				return;
			case CubeConfiguration.A | CubeConfiguration.C:
				return;
			case CubeConfiguration.B | CubeConfiguration.C:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C:
				return;
			case CubeConfiguration.D:
				return;
			case CubeConfiguration.A | CubeConfiguration.D:
				return;
			case CubeConfiguration.B | CubeConfiguration.D:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D:
				return;
			case CubeConfiguration.C | CubeConfiguration.D:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D:
				return;
			case CubeConfiguration.E:
				return;
			case CubeConfiguration.A | CubeConfiguration.E:
				return;
			case CubeConfiguration.B | CubeConfiguration.E:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.E:
				return;
			case CubeConfiguration.C | CubeConfiguration.E:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.E:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E:
				return;
			case CubeConfiguration.D | CubeConfiguration.E:
				return;
			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.E:
				return;
			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E:
				return;
			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E:
				return;
			case CubeConfiguration.F:
				return;
			case CubeConfiguration.A | CubeConfiguration.F:
				return;
			case CubeConfiguration.B | CubeConfiguration.F:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.F:
				return;
			case CubeConfiguration.C | CubeConfiguration.F:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.F:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.F:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.F:
				return;
			case CubeConfiguration.D | CubeConfiguration.F:
				return;
			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.F:
				return;
			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.F:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.F:
				return;
			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F:
				return;
			case CubeConfiguration.E | CubeConfiguration.F:
				return;
			case CubeConfiguration.A | CubeConfiguration.E | CubeConfiguration.F:
				return;
			case CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.F:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.F:
				return;
			case CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F:
				return;
			case CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F:
				return;
			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F:
				return;
			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F:
				return;
			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F:
				return;
			case CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.G:
				return;
			case CubeConfiguration.B | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.G:
				return;
			case CubeConfiguration.C | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.G:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.G:
				return;
			case CubeConfiguration.D | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.G:
				return;
			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.G:
				return;
			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.G:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.G:
				return;
			case CubeConfiguration.E | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.E | CubeConfiguration.G:
				return;
			case CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.G:
				return;
			case CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.G:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.G:
				return;
			case CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G:
				return;
			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G:
				return;
			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G:
				return;
			case CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.B | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G:
				return;
			case CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.H:
				return;
			case CubeConfiguration.C | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.H:
				return;
			case CubeConfiguration.D | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.H:
				return;
			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.H:
				return;
			case CubeConfiguration.E | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.E | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.H:
				return;
			case CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.H:
				return;
			case CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.H:
				return;
			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.H:
				return;
			case CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.H:
				return;
			case CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.C | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.D | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
			case CubeConfiguration.A | CubeConfiguration.B | CubeConfiguration.C | CubeConfiguration.D | CubeConfiguration.E | CubeConfiguration.F | CubeConfiguration.G | CubeConfiguration.H:
				return;
		}
	}
}
